<div class="row">
	<div class="col-sm-12">
		<?php if(strlen($this->warningmessage) > 0): ?>
			<div class="alert alert-danger">
				<?= $this->warningmessage ?>
			</div>
		<?php endif; ?>
		<?php if(strlen($this->message) > 0): ?>
			<div class="alert alert-success">
				<?= $this->message ?>
			</div>
		<?php endif; ?>
		<a href="/user/view" title="Back to Users">Back to Users</a>
	</div>
</div>
