<div class="row">
	<div class="col-sm-12">
		<h1><?= $this->user->firstname ?> <?= $this->user->surname ?> Statistics</h1>
		<div class="text-align-center top-buffer bottom-buffer">
			<div class="alert alert-info">
				<h1 class="final_balance"><strong>Remained balance</strong>: &euro;<?= number_format(floatval($this->user->calculateTotalExpenses()) 
+ floatval($this->user->calculateTotalSavings()),2) ?></h1>
			</div>	
		</div>

		<h2>Savings</h2>
		<div class="top-buffer bottom-buffer">
			<a class="btn btn-success" href="/saving/add">Add Saving</a>
		</div>
		<table class="table table-striped">
			<thead>
				<tr>
					<?php foreach(array_keys(SavingModel::$attributes) as $attribute): ?>
						<th><?= $attribute ?></th>
					<?php endforeach; ?>
						<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->user_savings as $saving): ?>
					<tr>
						<td><?= $saving->id ?></td>
						<td>&euro;<?= number_format($saving->saving_value,2) ?></td>
						<td><?= $saving->comment ?></td>
						<td><?php
							$user = UserModel::getMapper()->findOneBy("id",$saving->user_id);
							if($user){
								echo "<a href='/user/statistics/".$saving->user_id."' title='".$user->firstname." ".$user->surname."'>".$user->firstname." ".$user->surname."</a>";
							}
						?></td>
						<td><?= $saving->created_at ?></td>
						<td><?= $saving->updated_at ?></td>
						<td><a class="btn btn-info" href="/saving/edit/<?= $saving->id ?>">Edit</a> <a class="btn btn-danger" href="/saving/delete/<?= $saving->id ?>">Delete</a></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>

		<h2>Expenses</h2>
		<div class="top-buffer bottom-buffer">
			<a class="btn btn-success" href="/expense/add">Add Expense</a>
		</div>
		<table class="table table-striped">
			<thead>
				<tr>
					<?php foreach(array_keys(ExpenseModel::$attributes) as $attribute): ?>
						<th><?= $attribute ?></th>
					<?php endforeach; ?>
						<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->user_expenses as $expense): ?>
					<tr>
						<td><?= $expense->id ?></td>
						<td>&euro;<?= number_format($expense->expense_value,2) ?></td>
						<td><?= $expense->comment ?></td>
						<td><?php
							$user = UserModel::getMapper()->findOneBy("id",$expense->user_id);
							if($user){
								echo "<a href='/user/statistics/".$expense->user_id."' title='".$user->firstname." ".$user->surname."'>".$user->firstname." ".$user->surname."</a>";
							}
						?></td>
						<td><?= $expense->created_at ?></td>
						<td><?= $expense->updated_at ?></td>
						<td><a class="btn btn-info" href="/expense/edit/<?= $expense->id ?>">Edit</a> <a class="btn btn-danger" href="/expense/delete/<?= $expense->id ?>">Delete</a></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>


	</div>
</div>
