<div class="row">
	<div class="col-sm-12">
		<h1>Users</h1>
		<p>
			<a class="btn btn-success" href="/user/add">Add User</a>
		</p>
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<?php foreach($this->attributes as $attribute): ?>
						<th><?= $attribute ?></th>
					<?php endforeach; ?>
					<th>Actions</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach($this->users as $user): ?>
					<tr>
						<td><?= $user->id ?></td>
						<td><?= $user->title ?></td>
						<td><?= $user->firstname ?></td>
						<td><?= $user->surname ?></td>
						<td><?= $user->telephone ?></td>
						<td><?= $user->email ?></td>
						<td><?= $user->created_at ?></td>
						<td><?= $user->updated_at ?></td>
						<td>
							<a class="btn btn-info bottom-buffer" href="/user/statistics/<?= $user->id ?>">Statistics</a><br/>
							<a class="btn btn-info bottom-buffer" href="/user/edit/<?= $user->id ?>">Edit</a><br/>
							<a class="btn btn-danger bottom-buffer" href="/user/delete/<?= $user->id ?>">Delete</a><br/>
						</td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>
