<div class="row bottom-buffer">
	<div class="col-sm-12">
		<?php if(strlen($this->message) > 0): ?>
			<div class="alert alert-success">
				<?= $this->message ?>
			</div>
		<?php endif; ?>
		<?php if(strlen($this->warningmessage) > 0): ?>
			<div class="alert alert-danger">
				<?= $this->warningmessage ?>
			</div>
		<?php endif; ?>
		<form class="form-signin" action="/expense/add" method="post">
      <h2 class="form-signin-heading">Add Expense</h2>

			<div class="form-group">
		    <label for="expense_value">Expense value</label>
				<div class="input-group">
				  <span class="input-group-addon" id="sizing-addon1">&euro;</span>
			    <input type="number" step="0.01" id="expense_value" name="expense_value" class="form-control" placeholder="eg. 9.03" required="" autofocus="">
				</div>
			</div>

			<div class="form-group">
		    <label for="comment">Comment</label>
		    <textarea row="5" col="5" id="comment" name="comment" class="form-control" required="" autofocus=""></textarea>
			</div>

			<div class="form-group">
		    <label for="user_id">User</label>
				<select name="user_id" class="form-control" required>
					<?php foreach($this->users as $user): ?>
						<option value="<?= $user->id ?>"><?=$user->firstname ?> <?= $user->surname ?></option>
					<?php endforeach; ?>
				</select>
			</div>

      <button class="btn btn-primary " type="submit">Save</button>
    </form>
	</div>
</div>
