<div class="row">
	<div class="col-sm-12">
		<?php if(strlen($this->warningmessage) > 0): ?>
			<div class="alert alert-danger">
				<?= $this->warningmessage ?>
			</div>
		<?php endif; ?>
		<?php if($this->expense): ?>
			<h1>Are you sure you want to delete expense with ID <?= $this->expense->id ?>?</h1>
			<form class="form-signin" action="/expense/successDelete/<?= $this->expense->id ?>" method="post">
				<button class="btn btn-primary"  type="submit">Yes</button>
				<a class="btn btn-primary" href="/expense/view">No</a>
			</form>
		<?php endif; ?>
	</div>
</div>
